# Build configuration for WordPress Theme.
# -----
# Docker image from Docker Hub.
image: smartapps/bitbucket-pipelines-php-mysql
pipelines:
    branches:
        develop:
            - step:
                script:
                    - mkdir phpcs && curl -L https://github.com/squizlabs/PHP_CodeSniffer/archive/master.tar.gz | tar xz --strip-components=1 -C phpcs
                    - mkdir wpcs && curl -L https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/archive/master.tar.gz | tar xz --strip-components=1 -C wpcs
                    - cd phpcs
                    - scripts/phpcs --config-set installed_paths ../wpcs
                    - scripts/phpcs -p -s -v -n . --standard=../codesniffer.ruleset.xml --extensions=php --ignore=*/phpcs/*,*/wpcs/*
                    - cd ..
                    - cd .tools
                    - npm install
                    - gulp tests
        feature/*:
            - step:
                script:
                    - mkdir phpcs && curl -L https://github.com/squizlabs/PHP_CodeSniffer/archive/master.tar.gz | tar xz --strip-components=1 -C phpcs
                    - mkdir wpcs && curl -L https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/archive/master.tar.gz | tar xz --strip-components=1 -C wpcs
                    - cd phpcs
                    - scripts/phpcs --config-set installed_paths ../wpcs
                    - scripts/phpcs -p -s -v -n . --standard=../codesniffer.ruleset.xml --extensions=php --ignore=*/phpcs/*,*/wpcs/*
                    - cd ..
                    - cd .tools
                    - npm install
                    - gulp tests
